### ISSUE TITLE
Introduce improvements to the domain list view

### ISSUE THREAD

**Issue by korvoj** [nmaas-platform/nmaas-portal#48]
The domain list view (screenshot below) should be enhanced with:

- paging
- dynamic search based on domain name
- column sorting
- filtering of active/inactive domains

These features will make it easier to manage large number of domains, especially in use-cases such as the virtual lab.

![image](https://github.com/nmaas-platform/nmaas-portal/assets/4062681/6b6e1101-1deb-4e59-ab9d-ed600d6f0ca0)

**Comment by llopat** [comment]
@kbeyro please find my comments below.

Regarding the updates made to the Domains view:
- pagination controls should be on the right side (as on e.g. Users view)
- the icon indicating that a column is sorted (arrow) should be the same as on other similar views (e.g. `Users` view)
- it would be nice to have the domains sorted by codename by default so that the arrow is visible when users opens this view (this is to show that the column can be actually sorted)
- would it be possible to alter the mouse pointer after hovering over the column name to indicate that the name can be clicked in order to sort?
- we should add the "Domains per page" selector to be consistent with other views (e.g. `Users` view)
- from Vojdan's requirements what is missing is this the possibility to filter our deactivated domains (we could apply the same checkbox-based approach as for the `Application instances` view)

General remark is that we have several table/list-based views and we should should make them as consistent as possible:
- the search option added on the `Domains` view looks good and the same approach should be applied on the `Users` view
- we could add such search option on the `Applications` view and `Application instances` view
- on the `Users` view the `Users per page` selector should be moved blow the header and placed on the bar above the table (as on `Application instances` view)
